# Generated by Django 5.1.1 on 2024-11-16 13:07

import django.db.models.deletion
import django_jalali.db.models
import jdatetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_delete_blogview'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(default=jdatetime.date.today)),
                ('analytics_types', models.IntegerField(choices=[(0, 'No Type'), (1, 'daily'), (2, 'monthly')], default=0)),
                ('view', models.IntegerField(default=0)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogAnalytics', to='blog.blog')),
            ],
        ),
    ]
