# Generated by Django 5.1.1 on 2024-10-19 11:01

import django_jalali.db.models
import jdatetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4)),
                ('phonenumber', models.CharField(max_length=12, unique=True)),
                ('code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='adminInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=70)),
                ('displayName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('birthday_date', django_jalali.db.models.jDateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='adminLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=13)),
                ('joinedAt', django_jalali.db.models.jDateTimeField(default=jdatetime.datetime.now)),
                ('updatedAt', django_jalali.db.models.jDateTimeField(default=jdatetime.datetime.now)),
                ('lastLogin', django_jalali.db.models.jDateTimeField(default=jdatetime.datetime.now)),
            ],
        ),
    ]
