# Generated by Django 5.1.1 on 2024-10-19 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincodes',
            name='adminLogin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='adminCodes', to='adminstrator.adminlogin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminlogin',
            name='adminInformation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='adminLogin', to='adminstrator.admininformation'),
            preserve_default=False,
        ),
    ]
