# Generated by Django 5.1.1 on 2024-10-19 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0002_admincodes_adminlogin_adminlogin_admininformation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admincodes',
            old_name='phonenumber',
            new_name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='admincodes',
            name='adminLogin',
        ),
    ]
