# Generated by Django 5.1.1 on 2024-10-02 16:39

import blog.models
import ckeditor.fields
import django.db.models.deletion
import django_jalali.db.models
import jdatetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arrowpad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('poster', models.ImageField(upload_to=blog.models.blogPoster_path)),
                ('author', models.CharField(max_length=255)),
                ('brief', models.TextField()),
                ('content', ckeditor.fields.RichTextField()),
                ('url', models.URLField(max_length=255, unique=True)),
                ('publishedAt', django_jalali.db.models.jDateField(default=jdatetime.date.today)),
                ('updatedAt', django_jalali.db.models.jDateField(default=jdatetime.date.today)),
                ('hasVideo', models.BooleanField(default=False)),
                ('hasSlider', models.BooleanField(default=False)),
                ('isUpdated', models.BooleanField(default=False)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='arrowpad.categories')),
            ],
        ),
        migrations.CreateModel(
            name='blogMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metaTitle', models.CharField(max_length=255)),
                ('metaTags', models.CharField(max_length=255)),
                ('metaDescription', models.TextField()),
                ('metaKeywords', models.CharField(max_length=255)),
                ('blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blogMeta', to='blog.blog')),
            ],
        ),
        migrations.CreateModel(
            name='blogSlides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=blog.models.blogVideo_path)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogSlides', to='blog.blog')),
            ],
        ),
        migrations.CreateModel(
            name='blogVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=blog.models.blogVideo_path)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogVideos', to='blog.blog')),
            ],
        ),
    ]
