# Generated by Django 5.1.1 on 2024-10-15 15:50

import blog.models
import ckeditor.fields
import django.db.models.deletion
import django_jalali.db.models
import jdatetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arrowpad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('url', models.CharField(max_length=255, unique=True)),
                ('view', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('poster', models.ImageField(upload_to=blog.models.blogPoster_path)),
                ('posterWebp', models.ImageField(upload_to=blog.models.blogPosterWebp_path)),
                ('posterJpeg', models.ImageField(upload_to=blog.models.blogPosterJpeg_path)),
                ('author', models.CharField(max_length=255)),
                ('brief', models.TextField()),
                ('content', ckeditor.fields.RichTextField()),
                ('url', models.CharField(max_length=255, unique=True)),
                ('publishedAt', django_jalali.db.models.jDateField(default=jdatetime.date.today)),
                ('updatedAt', django_jalali.db.models.jDateField(default=jdatetime.date.today)),
                ('totalView', models.IntegerField(default=0)),
                ('hasVideo', models.BooleanField(default=False)),
                ('hasSlider', models.BooleanField(default=False)),
                ('isUpdated', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='arrowpad.categories')),
            ],
        ),
        migrations.CreateModel(
            name='blogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('comment', models.TextField()),
                ('jdate', django_jalali.db.models.jDateField(default=jdatetime.date.today)),
                ('active', models.BooleanField(default=False)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogComment', to='blog.blog')),
            ],
        ),
        migrations.CreateModel(
            name='blogMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metaTitle', models.CharField(max_length=255)),
                ('metaTags', models.CharField(max_length=255)),
                ('metaDescription', models.TextField()),
                ('metaKeywords', models.CharField(max_length=255)),
                ('blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blogMeta', to='blog.blog')),
            ],
        ),
        migrations.CreateModel(
            name='blogReplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.CharField(max_length=50)),
                ('reply', models.TextField()),
                ('jdate', django_jalali.db.models.jDateField(default=jdatetime.date.today)),
                ('active', models.BooleanField(default=False)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogReplies', to='blog.blog')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentReplies', to='blog.blogcomment')),
            ],
        ),
        migrations.CreateModel(
            name='blogSlides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=blog.models.blogSlides_path)),
                ('imageWebp', models.ImageField(upload_to=blog.models.blogSlidesWebp_path)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogSlides', to='blog.blog')),
            ],
        ),
        migrations.CreateModel(
            name='blogVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogVideos', to='blog.blog')),
            ],
        ),
        migrations.CreateModel(
            name='blogView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(default=jdatetime.date.today)),
                ('view', models.IntegerField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogView', to='blog.blog')),
            ],
        ),
    ]
