# Generated by Django 5.1.1 on 2024-10-04 15:45

import django.db.models.deletion
import django_jalali.db.models
import jdatetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(default=jdatetime.date.today)),
                ('view', models.IntegerField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogView', to='blog.blog')),
            ],
        ),
    ]
