# Generated by Django 5.1.1 on 2024-10-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogview'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogview',
            name='types',
            field=models.IntegerField(choices=[(0, 'Null'), (1, 'Total'), (2, 'Today')], default=0),
        ),
    ]
