# Generated by Django 5.1.1 on 2024-10-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogview_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogview',
            name='types',
        ),
        migrations.AddField(
            model_name='blog',
            name='totalView',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
