# Generated by Django 5.1.1 on 2024-10-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_blogview_types_blog_totalview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='totalView',
            field=models.IntegerField(default=0),
        ),
    ]
