# Generated by Django 5.1.1 on 2024-10-09 19:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_totalview'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('url', models.CharField(max_length=255, unique=True)),
                ('view', models.IntegerField()),
            ],
        ),
    ]
