# Generated by Django 5.1.1 on 2024-10-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtags',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
