# Generated by Django 5.1.1 on 2024-10-12 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blogcomment_blogreplies'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogreplies',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commentReplies', to='blog.blogcomment'),
            preserve_default=False,
        ),
    ]
