# Generated by Django 5.1.1 on 2024-10-12 19:15

import django_jalali.db.models
import jdatetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blogreplies_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='jdate',
            field=django_jalali.db.models.jDateField(default=jdatetime.date.today),
        ),
        migrations.AddField(
            model_name='blogreplies',
            name='jdate',
            field=django_jalali.db.models.jDateField(default=jdatetime.date.today),
        ),
    ]
