# Generated by Django 5.1.1 on 2024-10-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blogcomment_jdate_blogreplies_jdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogvideos',
            name='image',
        ),
        migrations.AddField(
            model_name='blogvideos',
            name='url',
            field=models.URLField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
