# Generated by Django 5.1.1 on 2024-10-02 16:39

import arrowpad.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4)),
                ('title', models.CharField(max_length=255)),
                ('vector', models.ImageField(upload_to=arrowpad.models.categoryVector_path)),
                ('brief', models.TextField()),
                ('url', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='categoryMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metaTitle', models.CharField(max_length=255)),
                ('metaTags', models.CharField(max_length=255)),
                ('metaDescription', models.TextField()),
                ('metaKeywords', models.CharField(max_length=255)),
            ],
        ),
    ]
