# Generated by Django 5.1.1 on 2024-10-22 12:34

import arrowpad.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4)),
                ('title', models.CharField(max_length=255)),
                ('en_name', models.CharField(max_length=255)),
                ('vector', models.ImageField(upload_to=arrowpad.models.categoryVector_path)),
                ('vectorWebp', models.ImageField(upload_to=arrowpad.models.categoryVectorWebp_path)),
                ('brief', models.TextField(blank=True, null=True)),
                ('url', models.CharField(max_length=255)),
                ('postCount', models.IntegerField(default=0)),
                ('youtubePlaylist', models.URLField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='categoryMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metaTitle', models.CharField(max_length=255)),
                ('metaTags', models.CharField(max_length=255)),
                ('metaDescription', models.TextField()),
                ('metaKeywords', models.CharField(max_length=255)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='categoryMeta', to='arrowpad.categories')),
            ],
        ),
    ]
