# Generated by Django 5.1.1 on 2024-10-02 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrowpad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='categorymeta',
            name='category',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categoryMeta', to='arrowpad.categories'),
            preserve_default=False,
        ),
    ]
