# Generated by Django 5.1.1 on 2024-10-19 11:01

import arrowpad.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrowpad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='vectorWebp',
            field=models.ImageField(upload_to=arrowpad.models.categoryVectorWebp_path),
        ),
    ]
