# Generated by Django 5.1.1 on 2024-11-02 16:40

import arrowpad.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrowpad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4)),
                ('title', models.CharField(max_length=255)),
                ('backgroundImage', models.ImageField(upload_to=arrowpad.models.bannerBackgroundImage_path)),
                ('rightImage', models.ImageField(blank=True, null=True, upload_to=arrowpad.models.bannerRightImage_path)),
                ('leftImage', models.ImageField(upload_to=arrowpad.models.bannerLeftImage_path)),
                ('btnText', models.CharField(blank=True, max_length=20, null=True)),
                ('btnUrl', models.URLField(blank=True, max_length=1000, null=True)),
                ('position', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
