# Generated by Django 5.1.1 on 2024-11-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrowpad', '0002_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='color',
            field=models.CharField(default='#000000', max_length=10),
        ),
    ]
