# Generated by Django 5.1.1 on 2024-10-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrowpad', '0002_categories_active_categorymeta_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='brief',
            field=models.TextField(blank=True, null=True),
        ),
    ]
