# Generated by Django 5.1.1 on 2024-10-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrowpad', '0003_alter_categories_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
