# Generated by Django 5.1.1 on 2024-10-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrowpad', '0004_alter_categories_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='youtubePlaylist',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
