# Generated by Django 5.1.1 on 2024-10-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrowpad', '0005_categories_youtubeplaylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='en_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
