# Generated by Django 5.1.1 on 2024-10-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrowpad', '0006_categories_en_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='postCount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
